docs(cce): fix docs issues.
FlexibleEngineCloud/terraform-provider-flexibleengine pull request #994
Opened 2023-09-07 12:02 UTC by wangzepeng666

fix docs issues.

2023-09-11 11:47 UTC, chengxiangdong commented on docs/resources/cce_cluster_v3.md
> +* `billing_mode` - (Optional, Int, ForceNew) Charging mode of the cluster, which is 0 (on demand).
FE does not require change mode arg.

2023-09-11 12:16 UTC, wangzepeng666 commented on docs/data-sources/cce_clusters.md
Referencing Huawei Cloud, not processed temporarily

2023-09-11 12:18 UTC, wangzepeng666 commented on docs/resources/cce_node_pool_v3.md
`scall_enable`  is deprecated
`extend_param`  declared in schema only, but it is not used

2023-09-11 12:21 UTC, chengxiangdong requested changes

2023-09-11 12:21 UTC, chengxiangdong commented on docs/data-sources/cce_node_v3.md
The validity of the arguments needs to be tested.

2023-09-11 12:21 UTC, chengxiangdong commented on docs/resources/cce_addon_v3.md
ditto

2023-09-11 12:21 UTC, chengxiangdong commented on docs/resources/cce_node_v3.md
ditto

2023-09-12 01:04 UTC, wangzepeng666 commented on docs/resources/cce_cluster_v3.md
> +* `billing_mode` - (Optional, Int, ForceNew) Charging mode of the cluster, which is 0 (on demand).
the schema and docs already existes

2023-09-12 01:10 UTC, wangzepeng666 commented on docs/data-sources/cce_node_v3.md
unit test has but docs miss the field

2023-09-12 01:10 UTC, wangzepeng666 commented on docs/data-sources/cce_node_v3.md
unit test has but docs miss the field

2023-09-12 01:11 UTC, wangzepeng666 commented on docs/resources/cce_addon_v3.md
ditto

2023-09-12 01:12 UTC, wangzepeng666 commented on docs/resources/cce_node_v3.md
unit test has but docs miss the field

2023-09-12 01:13 UTC, wangzepeng666 commented on docs/resources/cce_addon_v3.md
this docs have no field which is new added

2023-09-12 07:15 UTC, chengxiangdong commented on docs/data-sources/cce_clusters.md
`clusters.highway_subnet_id` does not exist in schema

2023-09-12 07:15 UTC, chengxiangdong commented on docs/resources/cce_node_v3.md
> +* `name` - (Optional, String, ForceNew) Node Name. Changing this parameter will create a new resource.
```suggestion
* `name` - (Optional, String) Node Name.
```

2023-09-12 07:28 UTC, wangzepeng666 commented on docs/resources/cce_node_v3.md
> +* `name` - (Optional, String, ForceNew) Node Name. Changing this parameter will create a new resource.
you have see wrong, name is forceNew

2023-09-15 07:00 UTC, chengxiangdong commented
/lgtm

2023-09-18 09:33 UTC, ShiChangkuo commented on docs/data-sources/cce_cluster_v3.md
> +* `name` -  (Optional, String)The Name of the cluster resource.
```suggestion
* `name` - (Optional, String)The Name of the cluster resource.
```

2023-09-18 11:29 UTC, merged