docs(css): fix docs issues.
FlexibleEngineCloud/terraform-provider-flexibleengine pull request #997
Opened 2023-09-08 07:26 UTC by wangzepeng666

fix docs issues.

2023-09-11 12:09 UTC, chengxiangdong requested changes

2023-09-11 12:09 UTC, chengxiangdong commented on docs/resources/css_cluster_v1.md
> +* `node_config` - (Required, Int) Specifies the node configuration. [node_config](#css_node_config_object) object
```suggestion
* `node_config` - (Required, List, ForceNew) Specifies the node configuration. [node_config](#css_node_config_object) object
```

2023-09-15 03:41 UTC, chengxiangdong commented
/lgtm

2023-09-18 09:39 UTC, ShiChangkuo commented on docs/resources/css_cluster_v1.md
> +  This parameter is mandatory only when security_mode is set to true.Changing this parameter will create a new resource.
```suggestion
  This parameter is mandatory only when security_mode is set to true. Changing this parameter will create a new resource.
```

2023-09-18 11:32 UTC, merged